<?PHP
session_start();
session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			About
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<p><strong>Background</strong><br /><br />
				<i>Homeroom</i> is a web-based room scheduling system developed at <a href="https://www.bowdoin.edu/computer-science/" TARGET="_BLANK">Bowdoin College</a> for the Ronald McDonald Houses in Portland and Bangor, Maine.   
				It was designed and implemented in 2011 and 2013 by Alex Lucyk, Jesus Navarro, Felix Emiliano, Luis Rojas, 
				David Phipps, Ruben Martinez, and Allen Tucker.  <i>Homeroom</i> is  supported by <a href="https://@npfi.org" target="_blank">NPFI</a>.
				<p><strong>System Access</strong><br /><br />
Because <i>Homeroom</i> must protect the privacy of individual clients at the Ronald McDonald House, access to the system is
limited.  If you have system access and have forgotten your Username or Password, please contact the House Manager.
                </p>
				<p> <i>Homeroom</i> is free and open source software. Its source code can be freely downloaded and adapted to support the room scheduling needs of other nonprofit organizations  
				(see <a href="https://github.com/megandalster/rmh-homeroomcivi/wiki" TARGET="_BLANK">https://github.com/megandalster/rmh-homeroomcivi/wiki</a>).  
				For more information about <i>Homeroom</i>, please visit the website <a href="https://npfi.org/the-homeroom-project" TARGET="_BLANK">https://npfi.org/the-homeroom-project</a>.
				</p>
				<!-- below is the footer that we're using currently-->
				
			</div><?PHP include('footer.inc');?>
		</div>
	</body>
</html>
