<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2011-2020 by:
	Felix Emiliano, Luis Rojas, David Phipps, Ruben Martinez, Alex Lucyk, Jesus Navarro, and Allen Tucker.<br />
	<i>Homeroom</i> was developed by <a href="https://npfi.org" target="_BLANK" style="font-weight:normal;">NPFI</a> and  
		  <a href="https://bowdoin.edu/computer-science" target="_BLANK" style="font-weight:normal;">Bowdoin College</a> 
	      for the <a href="http://www.rmhcmaine.org/" target="_BLANK" style="font-weight:normal;">Ronald McDonald House of Portland, ME</a>. 
	      It is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	      <a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;"> GNU General Public License</a>.
	</p>
</div>
</div>
<!-- End Footer -->