<?PHP
	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Help - <?PHP echo($_GET['helpPage']); ?>
		</title>
		<link rel="stylesheet" href="tutorial/styles.css" type="text/css" />
	</head>

	<body>
		<div id="container">
	<div id="content">
				<div align="left"><p><a href="?">Homeroom Help Index</a></p></div>

				<?PHP
					//This array associates pages a person might be viewing
					//with the help page we assume they want. Note: it might be important
					//for each page to include within it a link to the 'home help' website
					//to allow us to get them to material somewhere else they might want.
					//you can guarantee a link to the home site by simply linking to
					//help.php with no variable passed through the GET method.

					//basic pages
					$assocHelp['login.php']='login.inc.php';
					
					//managers and social workers
					$assocHelp['personEdit.php']='editPersonHelp.inc.php';
					$assocHelp['bookingEdit.php']='viewBookingsHelp.inc.php';
					$assocHelp['searchBookings.php']='searchBookingHelp.inc.php';
					$assocHelp['editPendingActiveBookings.php'] ='editBookingHelp.inc.php';
					$assocHelp['data.php']='dataHelp.inc.php';
					$assocHelp['searchPeople.php']='searchPersonHelp.inc.php';
					
					// managers and volunteers
					$assocHelp['room.php']='roomLogHelp.inc.php';
					$assocHelp['roomLog.php']='pastRoomLogsHelp.inc.php';
					
					//Now if we have an undefined array value for the key they've passed us,
					//we pass them to the index page to see if they can find help from there.
					if(!$assocHelp[$_GET['helpPage']])
						$assocHelp[$_GET['helpPage']]='index.inc.php';

					//now this line actually snags the tutorial data they're requesting and displays it.
					include('tutorial/'.$assocHelp[$_GET['helpPage']]);
				?>

				
			</div><?PHP include('footer.inc');?>
		</div>
	</body>
</html>
